[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shlex = "=1.2.0"
h2 = "=0.3.23"
# snow = "=0.9.4"
